config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  def index
    @flats = Flat.all
  end

  def show; end

  def new
    @flat = Flat.new # needed to instantiate the form_for
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save

    # no need for app/views/flats/create.html.erb
    redirect_to flat_path(@flat)
  end

  def edit; end

  def update
    @flat.update(flat_params)

    # no need for app/views/flats/update.html.erb
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy

    # no need for app/views/flats/destroy.html.erb
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:title, :content)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
  </div>

  <div class="form-actions mb-3">
    <%= f.button :submit, class: "btn btn-warning" %>
  </div>
<% end %>

app/views/flats/index.html.erb
<div class="container-fluid p-5">
  <div class="pl-4 row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1 class="text-dark">All our flats (<%= @flats.count %>)</h1>
      <div class="mt-5 d-flex flex-row justify-content-between flex-wrap">
        <% @flats.each do |flat| %>
        <div class="card text-dark mt-2 mb-2 mr-2 shadow-sm border-light" style="width: 20rem;">
          <div class="card-body bg-light">
            <h3 class="card-title"><%= flat.name %></h3>
            <p class="card-text text-muted"><%= flat.address %></p>
            <p class="card-text"><i class="fas fa-users"></i> <%= flat.price_per_night %> <i class="pl-1 fas fa-euro-sign"></i> <%= flat.price_per_night %></p>
          </div>
          <div class="card-footer bg-white">
              <%= link_to "+ info", flat_path(flat), class: "text-warning font-weight-bold" %>
            </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container mt-5">
  <h1 class="text-dark">New Flat</h1>

  <%= render 'form', flat: @flat %>
</div>

app/views/flats/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-7">
      <div class="card text-dark shadow-sm border-light mb-3">
        <div class="card-body bg-light">
          <h1 class="card-title font-weight-bold"><%= @flat.name %></h1>
          <h4 class="card-subtitle"><%= @flat.address %></h4>
        </div>
      </div>
      <div class="card text-dark shadow-sm border-light mb-3">
        <div class="card-body bg-light">
          <h3>A bit more about this flat...</h3>
          <p class="card-text"><%= @flat.description %></p>
        </div>
      </div>
      <div class="card text-dark shadow-sm border-light mb-3">
        <div class="card-body bg-light">
          <h3>Details</h3>
          <p class="card-text"><i class="fas fa-users"></i> <%= @flat.price_per_night %> <i class="pl-1 fas fa-euro-sign"></i> <%= @flat.price_per_night %></p>
        </div>
      </div>

      <div class="col-4">
        <div class="card text-dark shadow-sm border-light mb-3">
          <div class="card-body bg-light">
            <h3>Book this place!</h3>
            <p class="card-text"><%= @flat.description %></p>
          </div>
        </div>
        <div class="card text-dark shadow-sm border-light mb-3">
        <div class="card-body bg-light">
          <h5>Share</h5>
          <p class="card-text"><i class="fa fa-facebook-square fa-2x mr-2"></i>
            <i class="fa fa-twitter-square fa-2x mr-2"></i>
            <i class="fa fa-pinterest-square fa-2x mr-2"></i>
            <i class="fa fa-envelope-square fa-2x"></i>
          </p>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    </head>
  </head>

  <body class="bg-white">
      <nav class="navbar navbar-light bg-light">
            <%= link_to 'Simple Airbnb', flats_path, class: "navbar-brand display-4" %>
            <%= link_to 'Add Flat', new_flat_path, class: "btn btn-outline-warning my-2 my-lg-0" %>
          </nav>
          <%= yield %>
  </body>
</html>